"""Workspace identity, safe file access, navigation, and Git operations.

Internal modules use direct relative imports.  This package interface retains
the established ``api.workspace`` imports while keeping implementation and
mutable state with their semantic owners.
"""

# Re-exports are the package interface, including a small set of historical
# private path helpers still imported by existing callers.
# ruff: noqa: F401

from .file_access import dir_signature, list_dir, read_file_content
from .git import (
    GitWorkspaceError,
    WORKSPACE_GIT_DESTRUCTIVE_ENV,
    clean_generated_commit_message,
    git_branches,
    git_checkout,
    git_commit,
    git_commit_selected,
    git_diff,
    git_discard,
    git_fetch,
    git_info_for_workspace,
    git_pull,
    git_push,
    git_stage,
    git_stash_and_checkout,
    git_status,
    git_unstage,
    selected_commit_message_prompt,
    staged_commit_message_prompt,
    workspace_git_destructive_enabled,
)
from .navigation import (
    EscapeAuthorizationExpiredError,
    authorize_escape_target,
    list_authorized_escape_dir,
    raw_authorized_escape_target,
    read_authorized_escape_file_content,
    resolve_authorized_escape_request,
)
from .path_safety import (
    _DIR_FD_OK,
    _O_DIRECTORY,
    _O_NOFOLLOW,
    _USER_TMP_PREFIXES,
    _as_posix_path,
    _expanduser_path,
    _home_path,
    _is_blocked_posix_workspace_path,
    _is_blocked_system_path,
    _is_blocked_workspace_path,
    _is_within,
    _normalize_posix_path,
    _posix_is_within,
    _resolve_path,
    _safe_resolve,
    _strip_surrounding_quotes,
    _workspace_blocked_exact_roots,
    _workspace_blocked_resolved_subtrees,
    _workspace_blocked_roots,
    make_anchored_dir,
    open_anchored_create_fd,
    open_anchored_fd,
    open_anchored_write_fd,
    rename_anchored,
    rmtree_anchored,
    safe_resolve_ws,
    unlink_anchored,
)
from .registry import (
    _is_remote_terminal_backend,
    get_last_workspace,
    get_profile_default_workspace,
    list_workspace_suggestions,
    load_workspaces,
    resolve_trusted_workspace,
    save_workspaces,
    set_last_workspace,
    validate_workspace_to_add,
    is_remote_terminal_backend,
)

__all__ = [
    "EscapeAuthorizationExpiredError",
    "GitWorkspaceError",
    "WORKSPACE_GIT_DESTRUCTIVE_ENV",
    "authorize_escape_target",
    "clean_generated_commit_message",
    "dir_signature",
    "get_last_workspace",
    "get_profile_default_workspace",
    "git_branches",
    "git_checkout",
    "git_commit",
    "git_commit_selected",
    "git_diff",
    "git_discard",
    "git_fetch",
    "git_info_for_workspace",
    "git_pull",
    "git_push",
    "git_stage",
    "git_stash_and_checkout",
    "git_status",
    "git_unstage",
    "list_authorized_escape_dir",
    "list_dir",
    "list_workspace_suggestions",
    "is_remote_terminal_backend",
    "load_workspaces",
    "make_anchored_dir",
    "open_anchored_create_fd",
    "open_anchored_fd",
    "open_anchored_write_fd",
    "raw_authorized_escape_target",
    "read_authorized_escape_file_content",
    "read_file_content",
    "rename_anchored",
    "resolve_authorized_escape_request",
    "resolve_trusted_workspace",
    "rmtree_anchored",
    "safe_resolve_ws",
    "save_workspaces",
    "selected_commit_message_prompt",
    "set_last_workspace",
    "staged_commit_message_prompt",
    "unlink_anchored",
    "validate_workspace_to_add",
    "workspace_git_destructive_enabled",
]
