"""Compatibility interface for foreign-session projections.

New session code imports the owning modules directly. This stateless interface
keeps established imports working while all mutable caches remain owned once by
claude_code or external_sidebar.
"""

from .claude_code import (  # noqa: F401
    CLAUDE_CODE_MAX_CONTENT_CHARS,
    CLAUDE_CODE_MAX_FILES,
    CLAUDE_CODE_MAX_FILE_BYTES,
    CLAUDE_CODE_MAX_MESSAGES_PER_FILE,
    CLAUDE_CODE_SOURCE,
    CLAUDE_CODE_SOURCE_LABEL,
    _CLAUDE_CODE_PARSE_CACHE,
    _CLAUDE_CODE_PARSE_CACHE_LOCK,
    _CLAUDE_CODE_PARSE_CACHE_MAX,
    _claude_code_session_id,
    _claude_code_title,
    _default_claude_code_projects_dir,
    _extract_claude_code_text,
    _iter_claude_code_jsonl_files,
    _normalize_cli_session_source_filter,
    _parse_claude_code_jsonl,
    _parse_claude_code_jsonl_cached,
    _parse_claude_code_timestamp,
    clear_claude_code_parse_cache,
    get_claude_code_session_messages,
    get_claude_code_sessions,
)
from .external_sidebar import (  # noqa: F401
    CLI_VISIBLE_SESSION_LIMIT,
    CRON_PROJECT_CHIP_LIMIT,
    WEBHOOK_PROJECT_CHIP_LIMIT,
    _CLI_SESSIONS_CACHE,
    _CLI_SESSIONS_CACHE_INFLIGHT,
    _CLI_SESSIONS_CACHE_INVALIDATION_VERSION,
    _CLI_SESSIONS_CACHE_LOCK,
    _CLI_SESSIONS_CACHE_MAX_ENTRIES,
    _CLI_SESSIONS_CACHE_STALE_WAIT_SECONDS,
    _CLI_SESSIONS_CACHE_STREAMING_TTL_SECONDS,
    _CLI_SESSIONS_CACHE_TTL_SECONDS,
    _CLI_SESSIONS_CACHE_WAIT_SECONDS,
    _SIDECAR_METADATA_CACHE,
    _SIDECAR_METADATA_CACHE_LOCK,
    _SIDECAR_METADATA_CACHE_MAX,
    _all_profiles_cli_contexts,
    _cache_cli_sessions_if_current,
    _callable_accepts_include_claude_code,
    _cli_sessions_cache_claim_rebuild,
    _cli_sessions_cache_done,
    _cli_sessions_cache_invalidation_stamp,
    _cli_sessions_cache_ttl_seconds,
    _cli_sessions_streaming_freeze_marker,
    _copy_cli_sessions,
    _copy_fresh_cli_sessions_cache_entry,
    _load_and_cache_cli_sessions,
    _load_cli_sessions_uncached,
    _path_cache_key,
    _path_stat_cache_key,
    _reload_cli_sessions_after_inflight,
    _resolve_cli_sessions_context,
    _state_projection_sidecar_metadata,
    clear_cli_sessions_cache,
    clear_sidecar_metadata_cache,
    get_cli_sessions,
    logger,
)
from .gateway_identity import (  # noqa: F401
    gateway_session_identity,
    load_gateway_session_identity_map,
)
from .state_db import (  # noqa: F401
    _json_loads_if_string,
    get_state_db_session_message_keys_before_timestamp,
    get_state_db_session_message_prefix_summary,
    get_state_db_session_messages,
    get_state_db_session_summary,
    state_db_cache_key as _sqlite_file_stat_cache_key,
    state_db_content_fingerprint as _sqlite_content_fingerprint,
)
