"""Temporary compatibility imports for the workspace Git interface.

Production callers use :mod:`api.workspace`.  This module remains only for
legacy imports and owns no state or dispatch.
"""

# Compatibility re-exports intentionally include historical private helpers.
# ruff: noqa: F401

from api.workspace.git import (
    COMMIT_MESSAGE_DIFF_LIMIT,
    COMMIT_MESSAGE_SYSTEM_PROMPT,
    DIFF_SIZE_LIMIT,
    GIT_REMOTE_TIMEOUT,
    GIT_TIMEOUT,
    STATUS_FILE_LIMIT,
    WORKSPACE_GIT_DESTRUCTIVE_ENV,
    GitContext,
    GitWorkspaceError,
    _GIT_DESTRUCTIVE_HARDENED_CONFIG,
    _GIT_ENV_SCRUB_KEYS,
    _GIT_ENV_SCRUB_PREFIXES,
    _GIT_HARDENED_CONFIG,
    _LOCKS_GUARD,
    _OP_LOCKS,
    _block_filtered_destructive_write,
    _classify_git_error,
    _clean_git_env,
    _config_names_for_scope,
    _destructive_filter_overrides,
    _destructive_merge_driver_overrides,
    _destructive_remote_command_args,
    _destructive_remote_helper_overrides,
    _dirty_worktree,
    _filter_names_for_scope,
    _git_mutation_lock,
    _hardened_git_argv,
    _has_repo_local_filters,
    _merge_driver_names_for_scope,
    _remote_helper_names_for_scope,
    _repo_rel,
    _run_git,
    _windows_hide_flags,
    _workspace_pathspec,
    _workspace_rel,
    clean_generated_commit_message,
    git_branches,
    git_checkout,
    git_commit,
    git_commit_selected,
    git_diff,
    git_discard,
    git_fetch,
    git_pull,
    git_push,
    git_stage,
    git_stash_and_checkout,
    git_status,
    git_unstage,
    resolve_git_context,
    safe_resolve_ws,
    selected_commit_message_prompt,
    staged_commit_message_prompt,
    unlink_anchored,
    workspace_git_destructive_enabled,
)

__all__ = [
    "COMMIT_MESSAGE_DIFF_LIMIT",
    "COMMIT_MESSAGE_SYSTEM_PROMPT",
    "DIFF_SIZE_LIMIT",
    "GIT_REMOTE_TIMEOUT",
    "GIT_TIMEOUT",
    "GitContext",
    "GitWorkspaceError",
    "STATUS_FILE_LIMIT",
    "WORKSPACE_GIT_DESTRUCTIVE_ENV",
    "clean_generated_commit_message",
    "git_branches",
    "git_checkout",
    "git_commit",
    "git_commit_selected",
    "git_diff",
    "git_discard",
    "git_fetch",
    "git_pull",
    "git_push",
    "git_stage",
    "git_stash_and_checkout",
    "git_status",
    "git_unstage",
    "selected_commit_message_prompt",
    "staged_commit_message_prompt",
    "workspace_git_destructive_enabled",
]
